version: '3.9'

services:
  app:
    image: dada22/inventory-app:latest
    container_name: inventory_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: inventory
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
      /usr/local/bin/wait-for-it.sh db:3306 --timeout=30 --strict &&
      echo 'Database is up!' &&

      if [ ! -f .env ] || ! grep -q 'APP_KEY=base64:' .env; then
        echo 'Creating .env and generating APP_KEY...' &&
        cp .env.example .env &&
        php artisan key:generate --force
      fi &&

      echo 'Running migrations...' &&
      php artisan migrate --force &&

      echo 'Seeding database...' &&
      php artisan db:seed --force &&

      echo 'Starting Apache...' &&
      apache2-foreground
      "

  db:
    image: mysql:8
    container_name: inventory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
