version: '3.9'

services:
  app:
    image: dada22/inventory-app:latest
    container_name: inventory_app
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: inventory
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
      /usr/local/bin/wait-for-it.sh db:3306 -- &&
      if [ ! -s .env ] || ! grep -q 'APP_KEY=' .env; then 
        cp .env.example .env && 
        php artisan key:generate --force; 
      fi &&
      php artisan migrate --force &&
      php artisan db:seed --class=DatabaseSeeder &&
      apache2-foreground
      "

  db:
    image: mysql:8
    container_name: inventory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
